/* automatically generated by rust-bindgen */

pub const BOOTBOOT_MAGIC: &'static [u8; 5usize] = b"BOOT\0";
pub const PROTOCOL_MINIMAL: u32 = 0;
pub const PROTOCOL_STATIC: u32 = 1;
pub const PROTOCOL_DYNAMIC: u32 = 2;
pub const PROTOCOL_BIGENDIAN: u32 = 128;
pub const LOADER_BIOS: u32 = 0;
pub const LOADER_UEFI: u32 = 4;
pub const LOADER_RPI: u32 = 8;
pub const FB_ARGB: u32 = 0;
pub const FB_RGBA: u32 = 1;
pub const FB_ABGR: u32 = 2;
pub const FB_BGRA: u32 = 3;
pub const MMAP_USED: u32 = 0;
pub const MMAP_FREE: u32 = 1;
pub const MMAP_ACPI: u32 = 2;
pub const MMAP_MMIO: u32 = 3;
pub const INITRD_MAXSIZE: u32 = 16;

pub const BOOTBOOT_MMIO: u64 = 0xfffffffff8000000;  /* memory mapped IO virtual address */
pub const BOOTBOOT_FB: u64 = 0xfffffffffc000000;  /* frame buffer virtual address */
pub const BOOTBOOT_INFO: u64 = 0xffffffffff800000;  /* bootboot struct virtual address */
pub const BOOTBOOT_ENV: u64 = 0xffffffffff801000;  /* environment string virtual address */
pub const BOOTBOOT_CORE: u64 = 0xfffffffffe002000;  /* core loadable segment start */


#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct MMapEnt {
    pub ptr: u64,
    pub size: u64,
}

#[repr(C, packed)]
#[derive(Copy, Clone)]
pub struct BOOTBOOT {
    pub magic: [u8; 4usize],
    pub size: u32,
    pub protocol: u8,
    pub fb_type: u8,
    pub numcores: u16,
    pub bspid: u16,
    pub timezone: i16,
    pub datetime: [u8; 8usize],
    pub initrd_ptr: u64,
    pub initrd_size: u64,
    pub fb_ptr: *mut u8,
    pub fb_size: u32,
    pub fb_width: u32,
    pub fb_height: u32,
    pub fb_scanline: u32,
    pub arch: arch_union,
    pub mmap: MMapEnt,
}


#[repr(C)]
#[derive(Copy, Clone)]
pub union arch_union {
    pub x86_64: arch_x86,
    pub aarch64: arch_aarch64,
    _bindgen_union_align: [u64; 8usize],
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct arch_x86 {
    pub acpi_ptr: u64,
    pub smbi_ptr: u64,
    pub efi_ptr: u64,
    pub mp_ptr: u64,
    pub unused0: u64,
    pub unused1: u64,
    pub unused2: u64,
    pub unused3: u64,
}


#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct arch_aarch64 {
    pub acpi_ptr: u64,
    pub mmio_ptr: u64,
    pub efi_ptr: u64,
    pub unused0: u64,
    pub unused1: u64,
    pub unused2: u64,
    pub unused3: u64,
    pub unused4: u64,
}

/// Get the bootstrap processor ID from the BOOTBOOT structure
/// This is architecture-agnostic as it's provided by the bootloader
pub fn get_bootstrap_processor_id() -> u16 {
    let bootboot_r = unsafe { &(*(BOOTBOOT_INFO as *const BOOTBOOT)) };
    bootboot_r.bspid
}

/// Total number of CPU cores BOOTBOOT brought up (BSP + APs).
pub fn get_num_cores() -> u16 {
    let bootboot_r = unsafe { &(*(BOOTBOOT_INFO as *const BOOTBOOT)) };
    bootboot_r.numcores
}

/// Linear-framebuffer geometry as reported by BOOTBOOT. The
/// framebuffer is a physically-contiguous region of device memory;
/// `paddr` is its physical base (BOOTBOOT's `fb_ptr`, which the
/// loader fills with the GOP/VESA physical LFB address — the kernel
/// itself reaches the same pixels through the fixed higher-half
/// mapping at `BOOTBOOT_FB`). Exposed to userspace (extern-rootserver)
/// so a display component can map + drive the framebuffer.
#[cfg(feature = "extern-rootserver")]
#[derive(Copy, Clone, Debug)]
pub struct FramebufferInfo {
    /// Physical base address of the linear framebuffer.
    pub paddr: u64,
    /// Size in bytes (`fb_scanline * fb_height`, per BOOTBOOT).
    pub size: u32,
    pub width: u32,
    pub height: u32,
    /// Bytes per scanline (pitch). May exceed `width * 4` for padding.
    pub scanline: u32,
    /// Pixel format: one of `FB_ARGB`/`FB_RGBA`/`FB_ABGR`/`FB_BGRA`.
    pub fb_type: u8,
}

/// Read the BOOTBOOT framebuffer geometry. Returns `None` when the
/// loader reported no usable framebuffer (zero base, size, or
/// dimensions) — e.g. a truly headless boot with no GOP.
#[cfg(feature = "extern-rootserver")]
pub fn framebuffer_info() -> Option<FramebufferInfo> {
    let bootboot_r = unsafe { &(*(BOOTBOOT_INFO as *const BOOTBOOT)) };
    // `fb_ptr` is `*mut u8` in the packed struct; copy out of the
    // packed field before use to avoid an unaligned reference.
    let paddr = bootboot_r.fb_ptr as u64;
    let size = bootboot_r.fb_size;
    let width = bootboot_r.fb_width;
    let height = bootboot_r.fb_height;
    let scanline = bootboot_r.fb_scanline;
    let fb_type = bootboot_r.fb_type;
    if paddr == 0 || size == 0 || width == 0 || height == 0 {
        return None;
    }
    Some(FramebufferInfo { paddr, size, width, height, scanline, fb_type })
}
